server {
  listen 8080;
  server_name _;
  root /usr/share/nginx/html;
  index index.html;

  location /api/ {
    proxy_pass ${API_ORIGIN};
    proxy_http_version 1.1;
    proxy_ssl_server_name on;
    proxy_ssl_name $proxy_host;
    proxy_set_header Host $proxy_host;
    proxy_set_header X-Forwarded-Host $host;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Admin-IAP-JWT-Assertion $http_x_goog_iap_jwt_assertion;
  }

  location / {
    try_files $uri $uri/ /index.html;
  }
}
